### ISSUE TITLE
Having a config file crashes unless you pass -w

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/tattoo#40]
```
tattoo "PolymerElements/iron-input#2.0-preview"



TypeError: Cannot read property 'push' of undefined
    at mergeArray (/Users/noms/.nvm/versions/node/v6.9.1/lib/node_modules/tattoo/src/cli.ts:232:20)
    at Object.mergeConfigFileOptions (/Users/noms/.nvm/versions/node/v6.9.1/lib/node_modules/tattoo/src/cli.ts:249:3)
    at /Users/noms/.nvm/versions/node/v6.9.1/lib/node_modules/tattoo/src/bin/tattoo.ts:24:5
    at next (native)
    at /Users/noms/.nvm/versions/node/v6.9.1/lib/node_modules/tattoo/lib/bin/tattoo.js:8:65
    at __awaiter (/Users/noms/.nvm/versions/node/v6.9.1/lib/node_modules/tattoo/lib/bin/tattoo.js:4:12)
    at main (/Users/noms/.nvm/versions/node/v6.9.1/lib/node_modules/tattoo/lib/bin/tattoo.js:14:12)
    at Object.<anonymous> (/Users/noms/.nvm/versions/node/v6.9.1/lib/node_modules/tattoo/src/bin/tattoo.ts:51:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by usergenic** [comment]
Fixed in master
